extends Node2D

signal item_dropped
signal item_sold
signal item_purchased
signal item_too_expensive
signal too_many_modules
signal module_stacked
signal invalid_module_position
signal hull_placed_behind_propeller
signal hull_placed_above_or_below_scoop
